// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAocXtMQCtr_u_fZvJ2Nee7VBwRPD0Dg-U',
    appId: '1:876688672852:web:330ceb480d0aa9739d85c1',
    messagingSenderId: '876688672852',
    projectId: 'bwi-shein',
    authDomain: 'bwi-shein.firebaseapp.com',
    storageBucket: 'bwi-shein.appspot.com',
    measurementId: 'G-1KDLLJZXQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNohgBskCATYinH3i84NVgslPRKXT6yBc',
    appId: '1:876688672852:android:583f4d327a3aca839d85c1',
    messagingSenderId: '876688672852',
    projectId: 'bwi-shein',
    storageBucket: 'bwi-shein.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_GO7tBronC8GqTHP7PDuKzsle_YV5pUs',
    appId: '1:876688672852:ios:784ca5e0d3e6eed39d85c1',
    messagingSenderId: '876688672852',
    projectId: 'bwi-shein',
    storageBucket: 'bwi-shein.appspot.com',
    androidClientId:
        '876688672852-js0c8lovpbd4pos00talk28i30b5qkpf.apps.googleusercontent.com',
    iosBundleId: 'com.app.shein',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_GO7tBronC8GqTHP7PDuKzsle_YV5pUs',
    appId: '1:876688672852:ios:f26ba4c6c05471329d85c1',
    messagingSenderId: '876688672852',
    projectId: 'bwi-shein',
    storageBucket: 'bwi-shein.appspot.com',
    androidClientId:
        '876688672852-js0c8lovpbd4pos00talk28i30b5qkpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shein.RunnerTests',
  );
}
